export const enum ActionTypes {
  //APP
  SET_AUTH_DATA = 'USER/SET_AUTH_DATA',
  SET_USER_MAIN_INFO = 'USER/SET_USER_MAIN_INFO',
  GET_USER_MAIN_INFO = 'USER/GET_USER_MAIN_INFO',
  UPDATE_USER_MAIN_INFO = 'USER/UPDATE_USER_MAIN_INFO',
  CLEAR_USER_MAIN_INFO = 'USER/CLEAR_USER_MAIN_INFO',

  //AUTH
  LOGOUT = 'AUTH/LOGOUT',
  SET_IS_AUTH = 'AUTH/SET_IS_AUTH',
  SET_AUTH_LOADING = 'AUTH/SET_AUTH_LOADING',
  SET_AUTH_TYPE = 'AUTH/SET_AUTH_TYPE',
  LOGIN = 'AUTH/LOGIN',
  REGISTER = 'AUTH/REGISTER',

  //ANNOUNCEMENT
  CREATE_ANNOUNCEMENT = 'ANNOUNCEMENT/CREATE_ANNOUNCEMENT',
  UPDATE_ANNOUNCEMENT = 'ANNOUNCEMENT/UPDATE_ANNOUNCEMENT',
  DELETE_ANNOUNCEMENT = 'ANNOUNCEMENT/DELETE_ANNOUNCEMENT',
  GET_USER_ANNOUNCEMENTS = 'ANNOUNCEMENT/GET_USER_ANNOUNCEMENTS',
  GET_USER_ANNOUNCEMENTS_BY_ID = 'ANNOUNCEMENT/GET_USER_ANNOUNCEMENTS_BY_ID',
  GET_ALL_ANNOUNCEMENTS = 'ANNOUNCEMENT/GET_ALL_ANNOUNCEMENTS',
  SET_ALL_ANNOUNCEMENTS = 'ANNOUNCEMENT/SET_ALL_ANNOUNCEMENTS',
  SET_ALL_USER_ANNOUNCEMENTS = 'ANNOUNCEMENT/SET_ALL_USER_ANNOUNCEMENTS',
}
